### ISSUE TITLE
Kicked for wrong Slot

### ISSUE THREAD

**Issue by JjUust** [TaskForce47/TF47-Framework#4]
used a jet -y get out to rearm -< kicked out for wrong slot 

random Slots enters Jet -> gets kicked -> i can use it

**Comment by NeutraleNull** [comment]
Klingt nach einem Lokalitäts bedingten Fehler.
Leute ohne whitelist werden aber in jedem Fall gekickt?

**Comment by JjUust** [comment]
ja

**Comment by NeutraleNull** [comment]
Das reicht so leider nicht an Daten um das Problem weiter eingrenzen zu können. 
Ist das jedes mal zu repoduzieren?
Geht es beim zweiten einsteigen wieder?
Passiert das wieder wenn du aussteigst?
Was für ein Slot?

**Comment by JjUust** [comment]
Ok ganz von vorne. Fliege F-16 auf dem Pilotenslot -> Lande um neue Muni zu holen -> steige aus -> will wieder einsteigen -> werde rausgeworfen weil ich auf dem falschen Slot bin (mehrmals versucht) -> Desty als Helipilot steigt ein und wird auch rausgeworfen -> ich steige wieder ein und werde nicht rausgeworfen -> steige aus -> steige wieder ein und werde wieder geworfen (konnten es mehrmals reproduzieren)

**Comment by NeutraleNull** [comment]
Ich habe keinen Ahnung woran das liegt. Der Code hat eigentlich nichts lokalitätsbezogenes, das einzige was ich mir vorstellen könnte ist das der driver vom vehicle nicht updated und du somit "versuchst" auf einen crew slot zu steigen wofür du "keine" permission hast. Auch müsste es für alle anderen Fahrzeuge gelten unabhängig vom Typ.
